
#Bauxite Ore Worldgen
[bauxite_ore]
	#Enable/Disable Bauxite ore
	bauxiteOreEnabled = false
	#Min Y level
	#Range: -60 ~ 256
	minY = -60
	#Max Y Level
	#Range: -60 ~ 256
	maxY = 120
	#Ore vein count
	#Range: 1 ~ 100
	veinCount = 80
	#Ore vein size
	#Range: 1 ~ 10
	veinSize = 4

#Kepu Ore Worldgen
[kepu_ore]
	#Enable/Disable Kepu ore
	kepuOreEnabled = true
	#Min Y level
	#Range: -60 ~ 256
	minY = 0
	#Max Y Level
	#Range: -60 ~ 256
	maxY = 80
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 8
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 8

	[kepu_ore.modifiers]
		#Default Modifier Cap for adapting
		adaptingModifierCap = 10.0

